apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicinestockconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicineStockConfig
  template:
    metadata:
      labels:
        app: MedicineStockConfig
    spec:
      containers:
      - name: medicinestock
        image: dockcr.azurecr.io/medicinestockrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: medicinestockconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicineStockConfig
steps:
- task: DotNetCoreCLI@3
  inputs:
    command: test
    projects: '**/*Tests/MedicalStockModuleTest.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
