apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalrepresentativescheduleconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicalRepresentativeScheduleConfig
  template:
    metadata:
      labels:
        app: MedicalRepresentativeScheduleConfig
    spec:
      containers:
      - name: mrschedule
        image: dockcr.azurecr.io/mrschedule:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: medicalrepresentativescheduleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicalRepresentativeScheduleConfig
